# https://github.com/phusion/passenger-docker
FROM opendsa/opendsa-lti_base:1.0.0

RUN mkdir /home/app/OpenDSA-LTI
WORKDIR /home/app/OpenDSA-LTI
COPY . ./

RUN chown -R app:app /home/app/OpenDSA-LTI/
RUN chmod -R 775 /home/app/OpenDSA-LTI/

# expose the port
EXPOSE 80
EXPOSE 443