# https://github.com/phusion/passenger-docker
FROM opendsa/opendsa-lti_base

RUN mkdir /home/app/OpenDSA-LTI
WORKDIR /home/app/OpenDSA-LTI
COPY . ./

RUN bundle exec rake assets:precompile --trace

RUN chown -R app:app /home/app/OpenDSA-LTI/
RUN chmod -R 775 /home/app/OpenDSA-LTI/

# expose the port
EXPOSE 80
EXPOSE 443

ENV RACK_ENV production
ENV RAILS_ENV production
ENV PASSENGER_APP_ENV production